### ISSUE TITLE
test

### ISSUE THREAD

**Issue by wuhuizuo** [ti-community-infra/test-dev#531]
## General Question

- [x] this is a bug 

/sig yyy
/type bug

hello

**Comment by wuhuizuo** [comment]
1. [ ] 123

**Comment by zuo-bot-1** [comment]
@wuhuizuo: The label(s) `severity/major` cannot be applied. These labels are supported: `help wanted, good first issue, wontfix, high-performance, invalid, question, duplicate, documentation`.

<details>

In response to [this](https://github.com/ti-community-infra/test-dev/issues/531#issuecomment-1342583499):

>/label severity/major


Instructions for interacting with me using PR comments are available [here](https://prow.tidb.net/command-help).  If you have questions or suggestions related to my behavior, please file an issue against the [ti-community-infra/tichi](https://github.com/ti-community-infra/tichi/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zuo-bot-1** [comment]
@wuhuizuo: The label(s) `xxx` cannot be applied. These labels are supported: `help wanted, good first issue, wontfix, high-performance, invalid, question, duplicate, documentation`.

<details>

In response to [this](https://github.com/ti-community-infra/test-dev/issues/531#issuecomment-1342584152):

>/label xxx


Instructions for interacting with me using PR comments are available [here](https://prow.tidb.net/command-help).  If you have questions or suggestions related to my behavior, please file an issue against the [ti-community-infra/tichi](https://github.com/ti-community-infra/tichi/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zuo-bot-1** [comment]
@wuhuizuo: pong

<details>

Instructions for interacting with me using PR comments are available [here](https://prow.tidb.net/command-help).  If you have questions or suggestions related to my behavior, please file an issue against the [ti-community-infra/tichi](https://github.com/ti-community-infra/tichi/issues/new?title=Prow%20issue:) repository.
</details>
